name: Update README and Docs

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # every day at midnight UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run update_readme.py script
        run: |
          python scripts/update_readme.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md docs/problems_list.md
          git commit -m "Automated update of README and problems list" || echo "No changes to commit"
          git push
