name: Update LeetCode Progress

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * *'   # daily at 06:00 UTC (optional)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run update script
        run: python scripts/update_readme.py

      - name: Commit & Push (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/problems_list.md README.md || true
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update LeetCode progress"
            git push
          fi
